
advertised.listeners=PLAINTEXT://100.100.10.100:9098
listeners=PLAINTEXT://:9092,CONTROLLER://:9093
controller.quorum.voters=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
process.roles=broker,controller
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER
node.id=3
auto.create.topics.enable=false
min.insync.replicas=2
num.partitions=3
default.replication.factor=3